### ISSUE TITLE
Labels are not correct

### ISSUE THREAD

**Issue by dreambit** [MrZander/YoloMarkNet#4]
I opened labels generated by alexeyAB yolo_mark

![image](https://user-images.githubusercontent.com/1479661/54161954-ef141580-4464-11e9-9408-7760c7900abf.png)

As you can see labels are not properly displayed.

[000000298350.txt](https://github.com/MrZander/YoloMarkNet/files/2954444/000000298350.txt)
![000000298350](https://user-images.githubusercontent.com/1479661/54162201-b163bc80-4465-11e9-8187-af17eedd36b4.jpg)

**Comment by MrZander** [comment]
Hmm, I'll have to take a look.

**Comment by MrZander** [comment]
Finally got around to looking at this.

Looks like the file isn't right.

Line 9 is
`1 0.31884375 0.43010566 0.62125003 0.8518545`

Which corresponds to id, x, y, w, h expressed as a % of the image size
and y + h > 1.0, meaning that it is going to go outside the bounds.

I don't see any code issues, so I'm going to close this.
